# Discovering Disease Outbreaks from News Headlines

Identifying and mapping epidemics is crucial to prevent or respond to deadly disease outbreaks. Your first assignment for the WHO is as follows:

- Extract the locations (city and/or country name) from each news headline.
- Find the geographic coordinates of each headline using the city/country.
- Cluster (group) the headlines based on the geographic location.
- Visualize the clusters on a map and analyze them for patterns indicating an epidemic.
- Investigate the largest clusters for signs of disease outbreaks.
- Review headlines in the largest clusters within the United States and around the world. If any disease outbreak is   particularly dominant, visualize all worldwide mentions of that disease.
- Provide a summary of your findings to your superiors at the WHO so they can direct resources.

# 1. Parsing the News Headlines

**Objective**

Find any city and/or country names mentioned in each of the news headlines.

**Workflow**

1. Load in the headline data and examine it for any data quality issues.
1. Use any library/data structure to read in the headlines
1. Read through some of the headlines and identify potential problems
1. Using regular expressions and the cities and countries within the geonamescache library, match any cities/countries within each headline.
1. Make sure to normalize headlines and city/country names by removing accent marks. This can be done with the unidecode library.
1. Watch out for multiple cities in a headline and matches on short words! We want the match to be on the entire city—for example San Marino—and not a partial match—San.
1. Put the extracted data into a pandas DataFrame with three columns: headline, city, country.
1. Make sure there were no issues with the extraction by sampling some of the headlines and examining the city and country names.
1. One method for finding problems is to look for the most common names and see if there are any issues.
1. Once you are confident you’ve found all the cities/countries in each headline, save the DataFrame for the next part.

**Importance to project**

* We can’t do much with just the headlines; although they contain the city/country names, they do not contain the geographic information—latitude and longitude—we need to find clusters of disease outbreaks. The first step in getting the geographic information is to isolate the names.

* Later, we will use the names to find the location of each headline, which requires bringing in external data (through geonamescache).

* This workflow is common in data science. First, we separate the useful information from the noise—data mining—and then we augment it with external data—data engineering.

## Import all relevent libraries

In [35]:
# Regular expression
import re
from typing import Optional

# Data analysis and wrangling
import numpy as np
import pandas as pd

# Set display options for pandas
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("max_colwidth", None)

# Ignore warning
import warnings

## Visualization
# matplotlib
import matplotlib.pyplot as plt

# Normalized unicode data (to remove accents)
import unidecode

warnings.filterwarnings("ignore")

## Headline data

In [36]:
file_contents = ""
with open(r"Data\headlines.txt", "r") as file_handle:
    for line in file_handle.readlines():
        file_contents += line  # .replace("-", " ")


# View first 500 charactors
file_contents[:500]

'Zika Outbreak Hits Miami\nCould Zika Reach New York City?\nFirst Case of Zika in Miami Beach\nMystery Virus Spreads in Recife, Brazil\nDallas man comes down with case of Zika\nTrinidad confirms first Zika case\nZika Concerns are Spreading in Houston\nGeneve Scientists Battle to Find Cure\nThe CDC in Atlanta is Growing Worried\nZika Infested Monkeys in Sao Paulo\nBrownsville teen contracts Zika virus\nMosquito control efforts in St. Louis take new tactics with Zika threat\nSan Juan reports 1st U.S. Zika-rela'

In [37]:
# Create dataframe of headlines
df = (
    pd.DataFrame(file_contents.split("\n"), columns=["headline"])
    .sort_values(by="headline", ascending=True)
    .reset_index(drop=True)
)
print(df.info())
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   headline  650 non-null    object
dtypes: object(1)
memory usage: 5.2+ KB
None

                                                                  headline
0                                              18 new Zika Cases in Bogota
1                                            19 new Zika Cases in Sengkang
2                                 Alameda Residents Recieve Rabies vaccine
3             Albany Residents Recieve Respiratory Syncytial Virus vaccine
4                                    Antipolo under threat from Zika Virus
5                                        Arhus is infested with Bronchitis
6                                         Arvada is infested with Syphilis
7                                                      Authorities a Miami
8  Authorities are Worried about the Spread of Bronchitis in Silver Spring
9          Authorities are Worried about the Spread of Chickenpox in Hemet

#### Check the data quality of the `headlines`

> we will check for 
> - **duplicates**
> - **missing values**
> - **data types**

##### Duplicates check

In [38]:
df[df.duplicated(keep=False)]

                                 headline
421        Spanish Flu Outbreak in Lisbon
422        Spanish Flu Outbreak in Lisbon
424  Spanish Flu Spreading through Madrid
425  Spanish Flu Spreading through Madrid

> 📝**Note**: There were 2 duplicated headlines
>
> 💡 **Solution**: We will keep the first occurrence of the duplicated headlines and drop the rest.

###### Removes duplicates

In [39]:
# remove duplicates
df.drop_duplicates(subset="headline", keep="first", ignore_index=True, inplace=True)
print(df.shape)

(648, 1)

> 📝**Note**: We have 648 headlines remaining after removed 2 duplicated headlines.

##### Missing values check

In [40]:
df.headline.isnull().sum()

np.int64(0)

> 📝**Note**: No missing value in `headline`

##### Data types check

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 648 entries, 0 to 647
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   headline  648 non-null    object
dtypes: object(1)
memory usage: 5.2+ KB


###### change data type of headline to string

In [42]:
# This is important for the next step where we will use regex to extract city and country names
df.headline = df.headline.astype(dtype="string")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 648 entries, 0 to 647
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   headline  648 non-null    string
dtypes: string(1)
memory usage: 5.2 KB

#### Add headline IDs `headlineid`

In [43]:
# make sure that all headlines are unique
df.headline.nunique()

648

> 📝**Note**: `headline` has 648 unique values. All headlines are unique.

In [44]:
#  use index number as headlineid
df.reset_index(drop=False, names="headlineid", inplace=True)
#  change data type of headlineid to string
df.headlineid = df.headlineid.astype(dtype="string")
# Zero pad headlineid to 3 digits
df.headlineid = df.headlineid.str.zfill(width=3)

#### Normalize the `headline` column

In [45]:
df.headline = df.headline.apply(lambda x: unidecode.unidecode(x))

In [46]:
df

,headlineid,headline
0,000,18 new Zika Cases in Bogota
1,001,19 new Zika Cases in Sengkang
2,002,Alameda Residents Recieve Rabies vaccine
3,003,Albany Residents Recieve Respiratory Syncytial Virus vaccine
4,004,Antipolo under threat from Zika Virus
5,005,Arhus is infested with Bronchitis
6,006,Arvada is infested with Syphilis
7,007,Authorities a Miami
8,008,Authorities are Worried about the Spread of Bronchitis in Silver Spring
9,009,Authorities are Worried about the Spread of Chickenpox in Hemet
10,010,Authorities are Worried about the Spread of Chickenpox in Richmond
11,011,Authorities are Worried about the Spread of Dengue in Kingston
12,012,Authorities are Worried about the Spread of Gonorrhea in Taoyuan City
13,013,Authorities are Worried about the Spread of Hepatitis B in Yiwu
14,014,Authorities are Worried about the Spread of Hepatitis D in Akron
15,015,Authorities are Worried about the Spread of Hepatitis D in Ganja
16,016,Authorities are Worried about the Spread of Hepatitis D in North Bay
17,017,Authorities are Worried about the Spread of Influenza in Savannah
18,018,Authorities are Worried about the Spread of Mad Cow Disease in Edinburgh
19,019,Authorities are Worried about the Spread of Mad Cow Disease in Rome
20,020,Authorities are Worried about the Spread of Mumps in Corona
21,021,Authorities are Worried about the Spread of Norovirus in Buenos Aires
22,022,Authorities are Worried about the Spread of Norovirus in Dubai
23,023,Authorities are Worried about the Spread of Rotavirus in Union
24,024,Authorities are Worried about the Spread of Syphilis in Pyongyang
25,025,Authorities are Worried about the Spread of Tuberculosis in Abuja
26,026,Authorities are Worried about the Spread of Tuberculosis in Cantu
27,027,Authorities are Worried about the Spread of Varicella in Clovis
28,028,"BREAKING aEUR"" Zika in Missoula"
29,029,"Bad Water Leads to Sickness in Flint, Michigan"
30,030,Baltimore plans for Zika virus
31,031,Barcelona Struck by Spanish Flu
32,032,Barcelona Struck by Spanish Flu
33,033,Barstow Patient in Critical Condition after Contracting Herpes
34,034,Batangas Tourism Takes a Hit as Virus Spreads
35,035,Beijing team cracks Zika secret
36,036,Belize City under threat from Zika
37,037,Benton Residents Recieve Pneumonia vaccine
38,038,Biloxi Residents Recieve Chlamydia vaccine
39,039,Birmingham Residents Recieve Rabies vaccine
40,040,Bradenton Experiences Zika Troubles
41,041,Bridgeport authorities confirmed the spread of West Nile Virus
42,042,Brisbane is infested with Meningitis
43,043,Bronchitis Keeps Spreading in Hayward
44,044,Bronchitis Keeps Spreading in San Mateo
45,045,Bronchitis Outbreak in Manhasset
46,046,Bronchitis Symptoms Spread all over Santa Fe
47,047,Bronchitis re-emerges in Tehran
48,048,Brownsville teen contracts Zika virus
49,049,Can Zika make it here to Vero Beach?
50,050,Cancun hit by Outbreak of Party Fever!
51,051,Caracas patient dies
52,052,Carnival under threat in Rio De Janeiro due to Zika outbreak
53,053,Case of Chikungunya Reported in Gaithersburg
54,054,Case of Hepatitis A Reported in Calgary
55,055,Case of Hepatitis E Reported in Melbourne
56,056,Case of Mad Cow Disease Reported in Hilden
57,057,Case of Malaria Reported in Aurora
58,058,Case of Measles Reported in Springdale
59,059,Case of Measles Reported in Vancouver
60,060,Case of Mumps Reported in Dayton
61,061,Case of Norovirus Reported in Stratford
62,062,Case of Swine Flu Reported in Tbilisi
63,063,Case of Varicella Reported in Concord
64,064,Case of West Nile Virus Reported in Riverside
65,065,Chicago's First Zika Case Confirmed
66,066,Chickenpox Comes to Stillwater
67,067,Chickenpox Hits Simpsonville
68,068,Chickenpox has Arrived in Chula Vista
69,069,Chikungunya Exposure in Toledo
70,070,Chikungunya Hits Denver
71,071,Chikungunya Keeps Spreading in North Vancouver
72,072,Chikungunya has not Left Pismo Beach
73,073,Chikungunya re-emerges in Kobe
74,074,Chlamydia Exposure in Sanaa
75,075,Chlamydia Symptoms Spread all over University City
76,076,Cholera outbreak in Dakar
77,077,Contaminated Meat Brings Trouble for Bonn Farmers
78,078,Could Zika Reach New York City?
79,079,Dallas man comes down with case of Zika
80,080,Davenport is infested with Dengue
81,081,Deerfield tests new cure for Measles
82,082,Dengue Exposure in Kathmandu
83,083,Dengue Outbreak in Easton
84,084,Doral hit by Deadly Virus
85,085,Duisburg up in Arms over Mad Cow Disease
86,086,Duluth Patient in Critical Condition after Contracting Rotavirus
87,087,Durango is infested with Hepatitis B
88,088,Ebola outbreak in Kampala
89,089,El Paso fighting Zika
90,090,Erie County sets Zika traps
91,091,Escondido neighborhood to get sprayed for Zika virus
92,092,Fayetteville authorities confirmed the spread of HIV
93,093,First Case of Zika in Miami Beach
94,094,First Columbus Zika case
95,095,First Zika Case in Cincinnati
96,096,First Zika case confirmed in Yangon
97,097,"Flu outbreak in Galveston, Texas"
98,098,Flu season hits Boston
99,099,Fort Belvoir tests new cure for Hepatitis C
100,100,Fort Collins Encounters Severe Symptoms of Gonorrhea
101,101,Fort Hood Reports its First Zika Patient
102,102,Four cases of Zika in Hidalgo County
103,103,Framingham Residents Receive Measles vaccine
104,104,Frisco Woman Tests Positive For Zika Virus
105,105,Gainesville Deals with Disease Concerns
106,106,Geneve Scientists Battle to Find Cure
107,107,Germantown authorities confirmed the spread of Chickenpox
108,108,Gladstone Encounters Severe Symptoms of Dengue
109,109,Gonorrhea Exposure in Norwalk
110,110,Gonorrhea has Arrived in Avon Lake
111,111,Greenwich Establishes Zika Task Force
112,112,Guangzhou Patient in Critical Condition after Contracting Swine Flu
113,113,Gympie Patient in Critical Condition after Contracting Chlamydia
114,114,HIV Keeps Spreading in Boulder
115,115,HIV Symptoms Spread all over Hinthada
116,116,HIV has Arrived in Fairfax
117,117,HIV has Arrived in Tacoma
118,118,Halifax is infested with Swine Flu
119,119,Hallandale Beach a Victim of Zika Outbreak
120,120,Harare is infested with Pneumonia
121,121,Hepatitis A Vaccine is now Required in Fukushima
122,122,Hepatitis A has not Left Staten Island
123,123,Hepatitis A re-emerges in Foster City
124,124,Hepatitis A re-emerges in Stamford
125,125,Hepatitis B Comes to Kansas City
126,126,Hepatitis B Exposure in Edinburgh
127,127,Hepatitis B Vaccine is now Required in Quebec
128,128,Hepatitis B has not Left Florence
129,129,Hepatitis C Outbreak in Bethlehem
130,130,Hepatitis C Outbreak in Danbury
131,131,Hepatitis C re-emerges in Damascus
132,132,Hepatitis D Exposure in Aswan
133,133,Hepatitis D Keeps Spreading in Bismarck
134,134,Hepatitis D Keeps Spreading in Danvers
135,135,Hepatitis D Symptoms Spread all over Evansville
136,136,Hepatitis D Symptoms Spread all over North Bethesda
137,137,Hepatitis D has Arrived in Grenoble
138,138,Hepatitis E Hits Hammond
139,139,Hepatitis E has not Left Libreville
140,140,Hepatitis E re-emerges in Santa Rosa
141,141,Herpes Keeps Spreading in Rochester
142,142,Herpes Symptoms Spread all over Fremont
143,143,Herpes Symptoms Spread all over New Kingston
144,144,Herpes Vaccine is now Required in Mattoon
145,145,Hillsborough uses innovative trap against Zika 20 minutes ago
146,146,Hollywood Outbreak Film Premieres
147,147,Hospitals in Hanoi fill up with Zika patients
148,148,How to Avoid Chikungunya in Hampton
149,149,How to Avoid Chlamydia in Santiago
150,150,How to Avoid Contaminated Meat when Visiting Basel
151,151,How to Avoid Gonorrhea in Shreveport
152,152,How to Avoid Hepatitis B in Trenton
153,153,How to Avoid Hepatitis B in Waldorf
154,154,How to Avoid Hepatitis E in South Bend
155,155,How to Avoid Norovirus in Greenville
156,156,How to Avoid Pneumonia in Bullhead City
157,157,How to Avoid Respiratory Syncytial Virus in San Bernardino
158,158,How to Avoid Rhinovirus in Lemon Grove
159,159,How to Avoid Rhinovirus in Medford
160,160,How to Avoid Rhinovirus in Plainfield
161,161,How to Avoid Tuberculosis in Santa Monica
162,162,Huzhou Residents Receive Hepatitis B vaccine
163,163,Ibadan tests new cure for Malaria
164,164,Influenza Exposure in Muscat
165,165,Influenza Keeps Spreading in Suffolk
166,166,Influenza has not Left Sacramento
167,167,Iowa City Encounters Severe Symptoms of Rhinovirus
168,168,Is Lafayette prepared to combat Zika?
169,169,Is Zika virus in Majuro?
170,170,Ithaca is infested with Dengue
171,171,Jacksonville man hit by Zika
172,172,Johannesburg Patient in Critical Condition after Contracting Pneumonia
173,173,Kedougou tests new cure for Hepatitis C
174,174,Kent is infested with Rabies
175,175,Key Zika Findings in San Diego Institute
176,176,Kuala Lumpur is Hit By Zika Threat
177,177,Lausanne Residents Recieve Meningitis vaccine
178,178,Laventille authorities confirmed the spread of Rhinovirus
179,179,Lawrenceville is infested with Dengue
180,180,Lima tries to address Zika Concerns
181,181,London Health Unit Tracks Mad Cow Disease
182,182,Longwood volunteers spreading Zika awareness
183,183,Louisiana Zika cases up to 26
184,184,Lower Hospitalization in Auckland after Hepatitis D Vaccine becomes Mandatory
185,185,Lower Hospitalization in Dhaka after Measles Vaccine becomes Mandatory
186,186,Lower Hospitalization in Entebbe after Rabies Vaccine becomes Mandatory
187,187,Lower Hospitalization in Janesville after Varicella Vaccine becomes Mandatory
188,188,Lower Hospitalization in Lakewood after Hepatitis B Vaccine becomes Mandatory
189,189,Lower Hospitalization in Monroe after Hepatitis D Vaccine becomes Mandatory
190,190,Lower Hospitalization in Palm Springs after Hepatitis A Vaccine becomes Mandatory
191,191,Lower Hospitalization in Papeete after Measles Vaccine becomes Mandatory
192,192,Lower Hospitalization in Pekanbaru after Rotavirus Vaccine becomes Mandatory
193,193,Lower Hospitalization in Richmond after Mumps Vaccine becomes Mandatory
194,194,Lung Cancer Rates Increasing in Moscow
195,195,Mad Cow Disease Detected in Lyon
196,196,Mad Cow Disease Disastrous to Brussels
197,197,Mad Cow Disease Hits London
198,198,Mad Cow Disease Hits Naples
199,199,Mad Cow Disease Hits Rotterdam
200,200,Mad Cow Disease Re-emerges in Chatham
201,201,Mad Cow Disease Spreads to Margate
202,202,Mad Cow Disease re-emerges in Bedford
203,203,Mad Cow Outbreak Spreading in Ennis
204,204,Mad Cow case in Murcia
205,205,Madera Patient in Critical Condition after Contracting Rabies
206,206,Madison lab developing vaccine against Zika virus [The Wisconsin State Journal]
207,207,Maka City Experiences Influenza Outbreak
208,208,Malaria Exposure in Sussex
209,209,Malaria Outbreak Hits Zanzibar's Tourist Industry
210,210,Malaria Vaccine is now Required in Elyria
211,211,Malaria Vaccine is now Required in Schenectady
212,212,Malaria Vaccine is now Required in Winona
213,213,Malaria has Arrived in Terrebonne
214,214,Malaria is Spreading in Johannesburg
215,215,Malaria re-emerges in Boise
216,216,Malaria re-emerges in Nashua
217,217,Manassas Encounters Severe Symptoms of Measles
218,218,Manchester Residents Recieve Influenza vaccine
219,219,Mandaluyong City under Siege by Virus
220,220,Manhattan Residents Recieve HIV vaccine
221,221,Marquette tests new cure for Hepatitis A
222,222,Martinsville tests new cure for Measles
223,223,Measles Hits Davos
224,224,Measles Vaccine is now Required in Wailuku
225,225,Measles has not Left Brooklyn
226,226,Mecca tests new cure for Chikungunya
227,227,Memphis Encounters Severe Symptoms of Swine Flu
228,228,Meningitis re-emerges in Medina
229,229,Meningitis re-emerges in Nassau
230,230,Meningitis re-emerges in Summerville
231,231,Miami resident suggests Zika precautions
232,232,Milwaukee authorities confirmed the spread of Rhinovirus
233,233,Mobile authorities confirmed the spread of Bronchitis
234,234,Molo Cholera Spread Causing Concern
235,235,Montevideo Encounters Severe Symptoms of Rotavirus
236,236,More Livestock in Fontainebleau are infected with Mad Cow Disease
237,237,More Patients in Alexandria are Getting Diagnosed with Mumps
238,238,More Patients in Cambridge are Getting Diagnosed with Chickenpox
239,239,More Patients in Canton are Getting Diagnosed with Norovirus
240,240,More Patients in Crawfordsville are Getting Diagnosed with Rabies
241,241,More Patients in Dublin are Getting Diagnosed with Bronchitis
242,242,More Patients in Kensington are Getting Diagnosed with Varicella
243,243,More Patients in Magnolia are Getting Diagnosed with Malaria
244,244,More Patients in Maynard are Getting Diagnosed with Syphilis
245,245,More Patients in Orange are Getting Diagnosed with Chickenpox
246,246,More Patients in Stuttgart are Getting Diagnosed with Rabies
247,247,More Quezon City Zika Transmissions
248,248,More Zika cases in Soyapango
249,249,More Zika patients reported in Austin
250,250,More Zika patients reported in Bella Vista
251,251,More Zika patients reported in Botucatu
252,252,More Zika patients reported in Calumpang
253,253,More Zika patients reported in Camacari
254,254,More Zika patients reported in Carrollton
255,255,More Zika patients reported in Chanthaburi
256,256,More Zika patients reported in Chennai
257,257,More Zika patients reported in Custodia
258,258,More Zika patients reported in Davao
259,259,More Zika patients reported in Fort Myers
260,260,More Zika patients reported in Fort Worth
261,261,More Zika patients reported in Indang
262,262,More Zika patients reported in Joao Pessoa
263,263,More Zika patients reported in Kampong Speu
264,264,More Zika patients reported in Lakeland
265,265,More Zika patients reported in Mcallen
266,266,More Zika patients reported in Melbourne
267,267,More Zika patients reported in Nuevo Laredo
268,268,More Zika patients reported in Pensacola
269,269,More Zika patients reported in Ribeirao Preto
270,270,More Zika patients reported in Waco
271,271,More contaminated cattle reported in Bedford
272,272,More people in Allentown are infected with Chlamydia every year
273,273,More people in Berkeley are infected with Swine Flu every year
274,274,More people in Boucau are infected with HIV every year
275,275,More people in Cranford are infected with Hepatitis A every year
276,276,More people in Durham are infected with Chlamydia every year
277,277,More people in Huron are infected with Dengue every year
278,278,More people in Indianapolis are infected with Norovirus every year
279,279,More people in Kitwe are infected with Respiratory Syncytial Virus every year
280,280,More people in Mclean are infected with Hepatitis A every year
281,281,More people in Nadi are infected with HIV every year
282,282,More people in Oak Brook are infected with Respiratory Syncytial Virus every year
283,283,More people in Palo Alto are infected with HIV every year
284,284,More people in Saint Petersburg are infected with Varicella every year
285,285,More people in Toronto are infected with Hepatitis E every year
286,286,More people in Yokohama are infected with Norovirus every year
287,287,Mosquito control efforts in St. Louis take new tactics with Zika threat
288,288,Mpika authorities confirmed the spread of Chikungunya
289,289,Mumbai's Health Minister warns of more Zika cases
290,290,Mumps Hits Howard Beach
291,291,Mumps Outbreak in Joplin
292,292,Mumps Symptoms Spread all over Jefferson
293,293,"Mystery Virus Spreads in Recife, Brazil"
294,294,Nashville takes precautions against Zika
295,295,New Delhi Addressing Zika Concerns
296,296,New Los Angeles Hairstyle goes Viral
297,297,New Milford Patient in Critical Condition after Contracting Respiratory Syncytial Virus
298,298,New Vaccine on Trial in Bethesda District
299,299,New Zika Case Confirmed in Belo Horizonte
300,300,New Zika Case Confirmed in Sarasota County
301,301,"New Zika Case in Kota Kinabalu, Malaysia"
302,302,New details in Baton Rouge cop killings
303,303,New medicine wipes out Chikungunya in Tucson
304,304,New medicine wipes out Dengue in Saginaw
305,305,New medicine wipes out HIV in Kihei
306,306,New medicine wipes out Herpes in Bossier City
307,307,New medicine wipes out Influenza in Redlands
308,308,New medicine wipes out Measles in Fresno
309,309,New medicine wipes out Meningitis in Sevilla
310,310,New medicine wipes out Mumps in Saint Charles
311,311,New medicine wipes out Rabies in Newburgh
312,312,New medicine wipes out Tuberculosis in Taipei
313,313,New medicine wipes out West Nile Virus in Ventura
314,314,Nha Trang Zika Outbreak
315,315,Norfolk tests new cure for Herpes
316,316,Norovirus Exposure in Hong Kong
317,317,Norovirus Keeps Spreading in Copenhagen
318,318,Norovirus Vaccine is now Required in Anaheim
319,319,Norovirus has Arrived in Winnipeg
320,320,Northfield Encounters Severe Symptoms of Herpes
321,321,Norwalk Encounters Severe Symptoms of Malaria
322,322,Ogden is infested with Gonorrhea
323,323,Orlando volunteers aid Zika research
324,324,Outbreak of Zika in Alvorada
325,325,Outbreak of Zika in Bacolod City
326,326,Outbreak of Zika in Colombo
327,327,Outbreak of Zika in Corpus Christi
328,328,Outbreak of Zika in Destin
329,329,Outbreak of Zika in Hutchins
330,330,Outbreak of Zika in Kozhikode
331,331,Outbreak of Zika in Leesburg
332,332,Outbreak of Zika in Palm Springs
333,333,Outbreak of Zika in Panama City
334,334,Outbreak of Zika in Pasig City
335,335,Outbreak of Zika in Portoviejo
336,336,Outbreak of Zika in Santa Elena
337,337,Outbreak of Zika in Stephenville
338,338,Oxford tests new cure for HIV
339,339,Panama CityaEUR(tm)s first Zika related death
340,340,Pedro Juan Caballero Encounters Severe Symptoms of Pneumonia
341,341,Petaling Jaya man ill from Zika
342,342,Philadelphia experts track pandemic
343,343,Phnom Penh hit by Zika Threat
344,344,Phoenix Residents Recieve Syphilis vaccine
345,345,Pilsen Encounters Severe Symptoms of Malaria
346,346,Pittsburgh Residents Recieve Norovirus vaccine
347,347,Pneumonia Exposure in Alhambra
348,348,Pneumonia Exposure in San Jose
349,349,Pneumonia Outbreak in Springville
350,350,Pneumonia Symptoms Spread all over Bloomington
351,351,Pneumonia has not Left Kinshasa
352,352,Praia tests new cure for Pneumonia
353,353,Precautionary Zika measures in Rockhampton
354,354,Princeton Encounters Severe Symptoms of Dengue
355,355,Providence Encounters Severe Symptoms of Dengue
356,356,Pune woman diagnosed with Zika
357,357,Rabies Exposure in Hamilton
358,358,Rabies Hits Madrid
359,359,Rabies Outbreak in Altus
360,360,Respiratory Syncytial Virus Hits Henderson
361,361,Respiratory Syncytial Virus Keeps Spreading in Masaya
362,362,Respiratory Syncytial Virus Vaccine is now Required in Tulsa
363,363,Rhinovirus Comes to San Jose
364,364,Rhinovirus Hits Bakersfield
365,365,Rhinovirus has Arrived in Athens
366,366,Rhinovirus re-emerges in Storrs
367,367,Richland Center is infested with Hepatitis B
368,368,Rochester authorities confirmed the spread of Dengue
369,369,Ronkonkoma is infested with Chickenpox
370,370,Rotavirus Vaccine is now Required in Labasa
371,371,Rotavirus Vaccine is now Required in Las Cumbres
372,372,Rotavirus Vaccine is now Required in Starkville
373,373,Rumors about Bronchitis spreading in Bundaberg have been refuted
374,374,Rumors about Chlamydia spreading in Redmond have been refuted
375,375,Rumors about Dengue Spreading in Syracuse have been Refuted
376,376,Rumors about HIV spreading in Montpellier have been refuted
377,377,Rumors about Hepatitis C spreading in Darien have been refuted
378,378,Rumors about Hepatitis D Spreading in Montreal have been Refuted
379,379,Rumors about Hepatitis D Spreading in San Juan Capistrano have been Refuted
380,380,Rumors about Hepatitis D spreading in Albany have been refuted
381,381,Rumors about Hepatitis E Spreading in Morristown have been Refuted
382,382,Rumors about Influenza Spreading in Dobbs Ferry have been Refuted
383,383,Rumors about Mad Cow Disease Brighton have been Refuted
384,384,Rumors about Meningitis spreading in Guatemala City have been refuted
385,385,Rumors about Mumps Spreading in New Bedford have been Refuted

## GeonamesCache data

In [47]:
from geonamescache import GeonamesCache

"""
get_continents()
get_countries()
get_us_states()
get_cities()
get_countries_by_names()
get_us_states_by_names()
get_cities_by_name(name)
get_us_counties()
"""
gc = GeonamesCache()

### US states and counties

#### US states

In [48]:
states = pd.DataFrame(gc.get_us_states_by_names()).T.reset_index(drop=True)
states = states.sort_values(by="name", ascending=False).reset_index(drop=True)
states = states.rename(
    columns={"name": "statename", "code": "statecode", "geonameid": "stateid"}
)
# states.info()
print(states.shape)
states.head()

(51, 4)

  statecode      statename fips  stateid
0        WY        Wyoming   56  5843591
1        WI      Wisconsin   55  5279468
2        WV  West Virginia   54  4826850
3        WA     Washington   53  5815135
4        VA       Virginia   51  6254928

> 📝 **Note**: `states` dataFrame consits of 50 states and 1 district of Columbia

#### US Counties

In [49]:
# Retrive countynames data and create a dataframe.
counties = pd.DataFrame(gc.get_us_counties()).T.reset_index(drop=True).T

counties.columns = ["countyid", "countyname", "statecode"]
counties = counties.sort_values(
    by=["statecode", "countyname"], ascending=False
).reset_index(drop=True)
print(counties.shape)
counties.head(10)

(3235, 3)

  countyid         countyname statecode
0    56045      Weston County        WY
1    56043    Washakie County        WY
2    56041       Uinta County        WY
3    56039       Teton County        WY
4    56037  Sweetwater County        WY
5    56035    Sublette County        WY
6    56033    Sheridan County        WY
7    56031      Platte County        WY
8    56029        Park County        WY
9    56027    Niobrara County        WY

In [50]:
3225 - 3143

82

> 📝 **Note**: `counties` dataFrame consists of 3,225 counties in the US and its territories. The dataframe has 6 more statecodes and 92 more counies of the US territories.

In [51]:
counties.statecode.value_counts()

statecode
TX    254
GA    159
VA    134
KY    120
MO    115
KS    105
IL    102
NC    100
IA     99
TN     95
NE     93
IN     92
OH     88
MN     87
MI     83
MS     82
PR     78
OK     77
AR     75
WI     72
AL     67
FL     67
PA     67
SD     66
LA     64
CO     64
NY     62
CA     58
MT     56
WV     55
ND     53
SC     46
ID     44
WA     39
OR     36
NM     33
AK     29
UT     29
MD     24
WY     23
NJ     21
NV     17
ME     16
AZ     15
VT     14
MA     14
NH     10
CT      8
RI      5
HI      5
AS      5
MP      4
VI      3
DE      3
GU      1
DC      1
UM      1
Name: count, dtype: int64

In [52]:
states.statecode.nunique()

51

In [53]:
counties.statecode.nunique()

57

#### Merge US states and counties

In [54]:
# merge state and county dataframes

us_counties = (
    pd.merge(
        counties, states, on="statecode", how="left", suffixes=("_county", "_state")
    )
    .sort_values(by=["statename", "countyname"], ascending=False)
    .reset_index(drop=True)
)
us_counties = us_counties.rename(columns={"countyname": "county", "statename": "state"})

# Remove accents from county names
us_counties["county"] = us_counties["county"].apply(lambda x: unidecode.unidecode(x))

print(us_counties.shape)
us_counties.head()

(3235, 6)

  countyid             county statecode    state fips  stateid
0    56045      Weston County        WY  Wyoming   56  5843591
1    56043    Washakie County        WY  Wyoming   56  5843591
2    56041       Uinta County        WY  Wyoming   56  5843591
3    56039       Teton County        WY  Wyoming   56  5843591
4    56037  Sweetwater County        WY  Wyoming   56  5843591

In [55]:
# How many counties and states that have no state code in `states` dataframe?
us_counties[us_counties.state.isna()]

     countyid                         county statecode state fips stateid
3143    72153                Yauco Municipio        PR   NaN  NaN     NaN
3144    72151              Yabucoa Municipio        PR   NaN  NaN     NaN
3145    60050               Western District        AS   NaN  NaN     NaN
3146    72149             Villalba Municipio        PR   NaN  NaN     NaN
3147    72147              Vieques Municipio        PR   NaN  NaN     NaN
3148    72145            Vega Baja Municipio        PR   NaN  NaN     NaN
3149    72143            Vega Alta Municipio        PR   NaN  NaN     NaN
3150    72141               Utuado Municipio        PR   NaN  NaN     NaN
3151    72139        Trujillo Alto Municipio        PR   NaN  NaN     NaN
3152    72137             Toa Baja Municipio        PR   NaN  NaN     NaN
3153    72135             Toa Alta Municipio        PR   NaN  NaN     NaN
3154    69120            Tinian Municipality        MP   NaN  NaN     NaN
3155    60040                  Swains Island        AS   NaN  NaN     NaN
3156    78030              St. Thomas Island        VI   NaN  NaN     NaN
3157    78020                St. John Island        VI   NaN  NaN     NaN
3158    78010               St. Croix Island        VI   NaN  NaN     NaN
3159    72133         Santa Isabel Municipio        PR   NaN  NaN     NaN
3160    72131        San Sebastian Municipio        PR   NaN  NaN     NaN
3161    72129          San Lorenzo Municipio        PR   NaN  NaN     NaN
3162    72127             San Juan Municipio        PR   NaN  NaN     NaN
3163    72125           San German Municipio        PR   NaN  NaN     NaN
3164    72123              Salinas Municipio        PR   NaN  NaN     NaN
3165    69110            Saipan Municipality        MP   NaN  NaN     NaN
3166    72121        Sabana Grande Municipio        PR   NaN  NaN     NaN
3167    69100              Rota Municipality        MP   NaN  NaN     NaN
3168    60030                    Rose Island        AS   NaN  NaN     NaN
3169    72119           Rio Grande Municipio        PR   NaN  NaN     NaN
3170    72117               Rincon Municipio        PR   NaN  NaN     NaN
3171    72115         Quebradillas Municipio        PR   NaN  NaN     NaN
3172    72113                Ponce Municipio        PR   NaN  NaN     NaN
3173    72111             Penuelas Municipio        PR   NaN  NaN     NaN
3174    72109             Patillas Municipio        PR   NaN  NaN     NaN
3175    72107             Orocovis Municipio        PR   NaN  NaN     NaN
3176    69085  Northern Islands Municipality        MP   NaN  NaN     NaN
3177    72105            Naranjito Municipio        PR   NaN  NaN     NaN
3178    72103              Naguabo Municipio        PR   NaN  NaN     NaN
3179    72101              Morovis Municipio        PR   NaN  NaN     NaN
3180    72099                 Moca Municipio        PR   NaN  NaN     NaN
3181    74300                 Midway Islands        UM   NaN  NaN     NaN
3182    72097             Mayaguez Municipio        PR   NaN  NaN     NaN
3183    72095              Maunabo Municipio        PR   NaN  NaN     NaN
3184    72093              Maricao Municipio        PR   NaN  NaN     NaN
3185    60020                Manu'a District        AS   NaN  NaN     NaN
3186    72091               Manati Municipio        PR   NaN  NaN     NaN
3187    72089             Luquillo Municipio        PR   NaN  NaN     NaN
3188    72087                Loiza Municipio        PR   NaN  NaN     NaN
3189    72085          Las Piedras Municipio        PR   NaN  NaN     NaN
3190    72083           Las Marias Municipio        PR   NaN  NaN     NaN
3191    72081                Lares Municipio        PR   NaN  NaN     NaN
3192    72079                Lajas Municipio        PR   NaN  NaN     NaN
3193    72077               Juncos Municipio        PR   NaN  NaN     NaN
3194    72075           Juana Diaz Municipio        PR   NaN  NaN     NaN
3195    72073               Jayuya Municipio        PR   NaN  NaN     NaN
3196    72071              Isabela Municipio        PR   NaN  NaN     NaN
3197    72069              Humacao Municipio        PR   NaN  NaN     NaN
3198    72067          Hormigueros Municipio        PR   NaN  NaN     NaN
3199    72065              Hatillo Municipio        PR   NaN  NaN     NaN
3200    72063               Gurabo Municipio        PR   NaN  NaN     NaN
3201    72061             Guaynabo Municipio        PR   NaN  NaN     NaN
3202    72059           Guayanilla Municipio        PR   NaN  NaN     NaN
3203    72057              Guayama Municipio        PR   NaN  NaN     NaN
3204    72055              Guanica Municipio        PR   NaN  NaN     NaN
3205    66010                           Guam        GU   NaN  NaN     NaN
3206    72054              Florida Municipio        PR   NaN  NaN     NaN
3207    72053              Fajardo Municipio        PR   NaN  NaN     NaN
3208    60010               Eastern District        AS   NaN  NaN     NaN
3209    72051               Dorado Municipio        PR   NaN  NaN     NaN
3210    72049              Culebra Municipio        PR   NaN  NaN     NaN
3211    72047              Corozal Municipio        PR   NaN  NaN     NaN
3212    72045              Comerio Municipio        PR   NaN  NaN     NaN
3213    72043                Coamo Municipio        PR   NaN  NaN     NaN
3214    72041                Cidra Municipio        PR   NaN  NaN     NaN
3215    72039               Ciales Municipio        PR   NaN  NaN     NaN
3216    72037                Ceiba Municipio        PR   NaN  NaN     NaN
3217    72035                Cayey Municipio        PR   NaN  NaN     NaN
3218    72033               Catano Municipio        PR   NaN  NaN     NaN
3219    72031             Carolina Municipio        PR   NaN  NaN     NaN
3220    72029            Canovanas Municipio        PR   NaN  NaN     NaN
3221    72027                Camuy Municipio        PR   NaN  NaN     NaN
3222    72025               Caguas Municipio        PR   NaN  NaN     NaN
3223    72023            Cabo Rojo Municipio        PR   NaN  NaN     NaN
3224    72021              Bayamon Municipio        PR   NaN  NaN     NaN
3225    72019         Barranquitas Municipio        PR   NaN  NaN     NaN
3226    72017          Barceloneta Municipio        PR   NaN  NaN     NaN
3227    72015               Arroyo Municipio        PR   NaN  NaN     NaN
3228    72013              Arecibo Municipio        PR   NaN  NaN     NaN
3229    72011               Anasco Municipio        PR   NaN  NaN     NaN
3230    72009             Aibonito Municipio        PR   NaN  NaN     NaN
3231    72007         Aguas Buenas Municipio        PR   NaN  NaN     NaN
3232    72005            Aguadilla Municipio        PR   NaN  NaN     NaN
3233    72003               Aguada Municipio        PR   NaN  NaN     NaN
3234    72001             Adjuntas Municipio        PR   NaN  NaN     NaN

In [56]:
def remove_county_suffix(county: str) -> Optional[str]:
    """Remove common suffixes from county names."""
    s = [
        "County",
        "Municipality",
        "Municipio",
        "Census Area",
        "City and Borough",
        "Borough",
        "Parish",
    ]
    #  Create a regex pattern to match any of the suffixes

    regexs = "|".join(s)

    # Use regex to remove the suffixes
    county_name_only = re.sub(rf"\s*({regexs})\s*$", "", county, flags=re.IGNORECASE)
    return county_name_only.strip() if county_name_only else None


# Insert a new column for cleaned county names
us_counties.insert(loc=2, column="countyname", value=None)

# Apply the function to the 'county' column
us_counties["countyname"] = us_counties["county"].apply(remove_county_suffix)


print(counties.shape)


us_counties.head(10)

(3235, 3)

  countyid             county  countyname statecode    state fips  stateid
0    56045      Weston County      Weston        WY  Wyoming   56  5843591
1    56043    Washakie County    Washakie        WY  Wyoming   56  5843591
2    56041       Uinta County       Uinta        WY  Wyoming   56  5843591
3    56039       Teton County       Teton        WY  Wyoming   56  5843591
4    56037  Sweetwater County  Sweetwater        WY  Wyoming   56  5843591
5    56035    Sublette County    Sublette        WY  Wyoming   56  5843591
6    56033    Sheridan County    Sheridan        WY  Wyoming   56  5843591
7    56031      Platte County      Platte        WY  Wyoming   56  5843591
8    56029        Park County        Park        WY  Wyoming   56  5843591
9    56027    Niobrara County    Niobrara        WY  Wyoming   56  5843591

### Countries and cities

#### Countries

In [57]:
countries = pd.DataFrame(gc.get_countries_by_names()).T
# sort countries by name and reset index
countries = countries.sort_values(by="name", ascending=True).reset_index(drop=True)
# Rename columns for clarity
countries.rename(
    columns={"iso": "countrycode", "name": "countryname", "geonameid": "countryid"},
    inplace=True,
)

# countries.info()
print(countries.shape)
countries.head(10)

(252, 17)

,countryid,countryname,countrycode,iso3,isonumeric,fips,continentcode,capital,areakm2,population,tld,currencycode,currencyname,phone,postalcoderegex,languages,neighbours
0,1149361,Afghanistan,AF,AFG,4,AF,AS,Kabul,647500,37172386,.af,AFN,Afghani,93,,"fa-AF,ps,uz-AF,tk","TM,CN,IR,TJ,PK,UZ"
1,661882,Aland Islands,AX,ALA,248,,EU,Mariehamn,1580,26711,.ax,EUR,Euro,+358-18,^(?:FI)*(\d{5})$,sv-AX,
2,783754,Albania,AL,ALB,8,AL,EU,Tirana,28748,2866376,.al,ALL,Lek,355,^(\d{4})$,"sq,el","MK,GR,ME,RS,XK"
3,2589581,Algeria,DZ,DZA,12,AG,AF,Algiers,2381740,42228429,.dz,DZD,Dinar,213,^(\d{5})$,ar-DZ,"NE,EH,LY,MR,TN,MA,ML"
4,5880801,American Samoa,AS,ASM,16,AQ,OC,Pago Pago,199,55465,.as,USD,Dollar,+1-684,96799,"en-AS,sm,to",
5,3041565,Andorra,AD,AND,20,AN,EU,Andorra la Vella,468,77006,.ad,EUR,Euro,376,^(?:AD)*(\d{3})$,ca,"ES,FR"
6,3351879,Angola,AO,AGO,24,AO,AF,Luanda,1246700,30809762,.ao,AOA,Kwanza,244,,pt-AO,"CD,NA,ZM,CG"
7,3573511,Anguilla,AI,AIA,660,AV,NA,The Valley,102,13254,.ai,XCD,Dollar,+1-264,,en-AI,
8,6697173,Antarctica,AQ,ATA,10,AY,AN,,14000000,0,.aq,,,,,,
9,3576396,Antigua and Barbuda,AG,ATG,28,AC,NA,St. John's,443,96286,.ag,XCD,Dollar,+1-268,,en-AG,

In [58]:
# Keep only nessessary columns
countries = countries[["countryname", "capital", "countrycode", "countryid"]]

countries.head(10)

           countryname           capital countrycode countryid
0          Afghanistan             Kabul          AF   1149361
1        Aland Islands         Mariehamn          AX    661882
2              Albania            Tirana          AL    783754
3              Algeria           Algiers          DZ   2589581
4       American Samoa         Pago Pago          AS   5880801
5              Andorra  Andorra la Vella          AD   3041565
6               Angola            Luanda          AO   3351879
7             Anguilla        The Valley          AI   3573511
8           Antarctica                            AQ   6697173
9  Antigua and Barbuda        St. John's          AG   3576396

In [ ]:
# normalize country names to remove accents
countries.countryname = countries.countryname.apply(lambda x: unidecode.unidecode(x))

In [60]:
countries

,countryname,capital,countrycode,countryid
0,Afghanistan,Kabul,AF,1149361
1,Aland Islands,Mariehamn,AX,661882
2,Albania,Tirana,AL,783754
3,Algeria,Algiers,DZ,2589581
4,American Samoa,Pago Pago,AS,5880801
5,Andorra,Andorra la Vella,AD,3041565
6,Angola,Luanda,AO,3351879
7,Anguilla,The Valley,AI,3573511
8,Antarctica,,AQ,6697173
9,Antigua and Barbuda,St. John's,AG,3576396
10,Argentina,Buenos Aires,AR,3865483
11,Armenia,Yerevan,AM,174982
12,Aruba,Oranjestad,AW,3577279
13,Australia,Canberra,AU,2077456
14,Austria,Vienna,AT,2782113
15,Azerbaijan,Baku,AZ,587116
16,Bahamas,Nassau,BS,3572887
17,Bahrain,Manama,BH,290291
18,Bangladesh,Dhaka,BD,1210997
19,Barbados,Bridgetown,BB,3374084
20,Belarus,Minsk,BY,630336
21,Belgium,Brussels,BE,2802361
22,Belize,Belmopan,BZ,3582678
23,Benin,Porto-Novo,BJ,2395170
24,Bermuda,Hamilton,BM,3573345
25,Bhutan,Thimphu,BT,1252634
26,Bolivia,Sucre,BO,3923057
27,"Bonaire, Saint Eustatius and Saba",,BQ,7626844
28,Bosnia and Herzegovina,Sarajevo,BA,3277605
29,Botswana,Gaborone,BW,933860
30,Bouvet Island,,BV,3371123
31,Brazil,Brasilia,BR,3469034
32,British Indian Ocean Territory,Diego Garcia,IO,1282588
33,British Virgin Islands,Road Town,VG,3577718
34,Brunei,Bandar Seri Begawan,BN,1820814
35,Bulgaria,Sofia,BG,732800
36,Burkina Faso,Ouagadougou,BF,2361809
37,Burundi,Gitega,BI,433561
38,Cabo Verde,Praia,CV,3374766
39,Cambodia,Phnom Penh,KH,1831722
40,Cameroon,Yaounde,CM,2233387
41,Canada,Ottawa,CA,6251999
42,Cayman Islands,George Town,KY,3580718
43,Central African Republic,Bangui,CF,239880
44,Chad,N'Djamena,TD,2434508
45,Chile,Santiago,CL,3895114
46,China,Beijing,CN,1814991
47,Christmas Island,Flying Fish Cove,CX,2078138
48,Cocos Islands,West Island,CC,1547376
49,Colombia,Bogota,CO,3686110
50,Comoros,Moroni,KM,921929
51,Cook Islands,Avarua,CK,1899402
52,Costa Rica,San Jose,CR,3624060
53,Croatia,Zagreb,HR,3202326
54,Cuba,Havana,CU,3562981
55,Curacao,Willemstad,CW,7626836
56,Cyprus,Nicosia,CY,146669
57,Czechia,Prague,CZ,3077311
58,Democratic Republic of the Congo,Kinshasa,CD,203312
59,Denmark,Copenhagen,DK,2623032
60,Djibouti,Djibouti,DJ,223816
61,Dominica,Roseau,DM,3575830
62,Dominican Republic,Santo Domingo,DO,3508796
63,Ecuador,Quito,EC,3658394
64,Egypt,Cairo,EG,357994
65,El Salvador,San Salvador,SV,3585968
66,Equatorial Guinea,Malabo,GQ,2309096
67,Eritrea,Asmara,ER,338010
68,Estonia,Tallinn,EE,453733
69,Eswatini,Mbabane,SZ,934841
70,Ethiopia,Addis Ababa,ET,337996
71,Falkland Islands,Stanley,FK,3474414
72,Faroe Islands,Torshavn,FO,2622320
73,Fiji,Suva,FJ,2205218
74,Finland,Helsinki,FI,660013
75,France,Paris,FR,3017382
76,French Guiana,Cayenne,GF,3381670
77,French Polynesia,Papeete,PF,4030656
78,French Southern Territories,Port-aux-Francais,TF,1546748
79,Gabon,Libreville,GA,2400553
80,Gambia,Banjul,GM,2413451
81,Georgia,Tbilisi,GE,614540
82,Germany,Berlin,DE,2921044
83,Ghana,Accra,GH,2300660
84,Gibraltar,Gibraltar,GI,2411586
85,Greece,Athens,GR,390903
86,Greenland,Nuuk,GL,3425505
87,Grenada,St. George's,GD,3580239
88,Guadeloupe,Basse-Terre,GP,3579143
89,Guam,Hagatna,GU,4043988
90,Guatemala,Guatemala City,GT,3595528
91,Guernsey,St Peter Port,GG,3042362
92,Guinea,Conakry,GN,2420477
93,Guinea-Bissau,Bissau,GW,2372248
94,Guyana,Georgetown,GY,3378535
95,Haiti,Port-au-Prince,HT,3723988
96,Heard Island and McDonald Islands,,HM,1547314
97,Honduras,Tegucigalpa,HN,3608932
98,Hong Kong,Hong Kong,HK,1819730
99,Hungary,Budapest,HU,719819
100,Iceland,Reykjavik,IS,2629691
101,India,New Delhi,IN,1269750
102,Indonesia,Jakarta,ID,1643084
103,Iran,Tehran,IR,130758
104,Iraq,Baghdad,IQ,99237
105,Ireland,Dublin,IE,2963597
106,Isle of Man,Douglas,IM,3042225
107,Israel,Jerusalem,IL,294640
108,Italy,Rome,IT,3175395
109,Ivory Coast,Yamoussoukro,CI,2287781
110,Jamaica,Kingston,JM,3489940
111,Japan,Tokyo,JP,1861060
112,Jersey,Saint Helier,JE,3042142
113,Jordan,Amman,JO,248816
114,Kazakhstan,Nur-Sultan,KZ,1522867
115,Kenya,Nairobi,KE,192950
116,Kiribati,Tarawa,KI,4030945
117,Kosovo,Pristina,XK,831053
118,Kuwait,Kuwait City,KW,285570
119,Kyrgyzstan,Bishkek,KG,1527747
120,Laos,Vientiane,LA,1655842
121,Latvia,Riga,LV,458258
122,Lebanon,Beirut,LB,272103
123,Lesotho,Maseru,LS,932692
124,Liberia,Monrovia,LR,2275384
125,Libya,Tripoli,LY,2215636
126,Liechtenstein,Vaduz,LI,3042058
127,Lithuania,Vilnius,LT,597427
128,Luxembourg,Luxembourg,LU,2960313
129,Macao,Macao,MO,1821275
130,Madagascar,Antananarivo,MG,1062947
131,Malawi,Lilongwe,MW,927384
132,Malaysia,Kuala Lumpur,MY,1733045
133,Maldives,Male,MV,1282028
134,Mali,Bamako,ML,2453866
135,Malta,Valletta,MT,2562770
136,Marshall Islands,Majuro,MH,2080185
137,Martinique,Fort-de-France,MQ,3570311
138,Mauritania,Nouakchott,MR,2378080
139,Mauritius,Port Louis,MU,934292
140,Mayotte,Mamoudzou,YT,1024031
141,Mexico,Mexico City,MX,3996063
142,Micronesia,Palikir,FM,2081918
143,Moldova,Chisinau,MD,617790
144,Monaco,Monaco,MC,2993457
145,Mongolia,Ulaanbaatar,MN,2029969
146,Montenegro,Podgorica,ME,3194884
147,Montserrat,Plymouth,MS,3578097
148,Morocco,Rabat,MA,2542007
149,Mozambique,Maputo,MZ,1036973
150,Myanmar,Nay Pyi Taw,MM,1327865
151,Namibia,Windhoek,NA,3355338
152,Nauru,Yaren,NR,2110425
153,Nepal,Kathmandu,NP,1282988
154,Netherlands,Amsterdam,NL,2750405
155,Netherlands Antilles,Willemstad,AN,8505032
156,New Caledonia,Noumea,NC,2139685
157,New Zealand,Wellington,NZ,2186224
158,Nicaragua,Managua,NI,3617476
159,Niger,Niamey,NE,2440476
160,Nigeria,Abuja,NG,2328926
161,Niue,Alofi,NU,4036232
162,Norfolk Island,Kingston,NF,2155115
163,North Korea,Pyongyang,KP,1873107
164,North Macedonia,Skopje,MK,718075
165,Northern Mariana Islands,Saipan,MP,4041468
166,Norway,Oslo,NO,3144096
167,Oman,Muscat,OM,286963
168,Pakistan,Islamabad,PK,1168579
169,Palau,Melekeok,PW,1559582
170,Palestinian Territory,East Jerusalem,PS,6254930
171,Panama,Panama City,PA,3703430
172,Papua New Guinea,Port Moresby,PG,2088628
173,Paraguay,Asuncion,PY,3437598
174,Peru,Lima,PE,3932488
175,Philippines,Manila,PH,1694008
176,Pitcairn,Adamstown,PN,4030699
177,Poland,Warsaw,PL,798544
178,Portugal,Lisbon,PT,2264397
179,Puerto Rico,San Juan,PR,4566966
180,Qatar,Doha,QA,289688
181,Republic of the Congo,Brazzaville,CG,2260494
182,Reunion,Saint-Denis,RE,935317
183,Romania,Bucharest,RO,798549
184,Russia,Moscow,RU,2017370
185,Rwanda,Kigali,RW,49518
186,Saint Barthelemy,Gustavia,BL,3578476
187,Saint Helena,Jamestown,SH,3370751
188,Saint Kitts and Nevis,Basseterre,KN,3575174
189,Saint Lucia,Castries,LC,3576468
190,Saint Martin,Marigot,MF,3578421
191,Saint Pierre and Miquelon,Saint-Pierre,PM,3424932
192,Saint Vincent and the Grenadines,Kingstown,VC,3577815
193,Samoa,Apia,WS,4034894
194,San Marino,San Marino,SM,3168068
195,Sao Tome and Principe,Sao Tome,ST,2410758
196,Saudi Arabia,Riyadh,SA,102358
197,Senegal,Dakar,SN,2245662
198,Serbia,Belgrade,RS,6290252
199,Serbia and Montenegro,Belgrade,CS,8505033
200,Seychelles,Victoria,SC,241170
201,Sierra Leone,Freetown,SL,2403846
202,Singapore,Singapore,SG,1880251
203,Sint Maarten,Philipsburg,SX,7609695
204,Slovakia,Bratislava,SK,3057568
205,Slovenia,Ljubljana,SI,3190538
206,Solomon Islands,Honiara,SB,2103350
207,Somalia,Mogadishu,SO,51537
208,South Africa,Pretoria,ZA,953987
209,South Georgia and the South Sandwich Islands,Grytviken,GS,3474415
210,South Korea,Seoul,KR,1835841
211,South Sudan,Juba,SS,7909807
212,Spain,Madrid,ES,2510769
213,Sri Lanka,Colombo,LK,1227603
214,Sudan,Khartoum,SD,366755
215,Suriname,Paramaribo,SR,3382998
216,Svalbard and Jan Mayen,Longyearbyen,SJ,607072
217,Sweden,Stockholm,SE,2661886
218,Switzerland,Bern,CH,2658434
219,Syria,Damascus,SY,163843
220,Taiwan,Taipei,TW,1668284
221,Tajikistan,Dushanbe,TJ,1220409
222,Tanzania,Dodoma,TZ,149590
223,Thailand,Bangkok,TH,1605651
224,Timor Leste,Dili,TL,1966436
225,Togo,Lome,TG,2363686
226,Tokelau,,TK,4031074
227,Tonga,Nuku'alofa,TO,4032283
228,Trinidad and Tobago,Port of Spain,TT,3573591
229,Tunisia,Tunis,TN,2464461
230,Turkey,Ankara,TR,298795
231,Turkmenistan,Ashgabat,TM,1218197
232,Turks and Caicos Islands,Cockburn Town,TC,3576916
233,Tuvalu,Funafuti,TV,2110297
234,U.S. Virgin Islands,Charlotte Amalie,VI,4796775
235,Uganda,Kampala,UG,226074
236,Ukraine,Kyiv,UA,690791
237,United Arab Emirates,Abu Dhabi,AE,290557
238,United Kingdom,London,GB,2635167
239,United States,Washington,US,6252001
240,United States Minor Outlying Islands,,UM,5854968
241,Uruguay,Montevideo,UY,3439705
242,Uzbekistan,Tashkent,UZ,1512440
243,Vanuatu,Port Vila,VU,2134431
244,Vatican,Vatican City,VA,3164670
245,Venezuela,Caracas,VE,3625428
246,Vietnam,Hanoi,VN,1562822
247,Wallis and Futuna,Mata Utu,WF,4034749
248,Western Sahara,El-Aaiun,EH,2461445
249,Yemen,Sanaa,YE,69543
250,Zambia,Lusaka,ZM,895949
251,Zimbabwe,Harare,ZW,878675

#### Cities

In [61]:
# create a dataframe for cities
cities = pd.DataFrame(gc.get_cities()).T.reset_index(drop=True)
print(cities.shape)
cities.head()

(26463, 9)

,geonameid,name,latitude,longitude,countrycode,population,timezone,admin1code,alternatenames
0,3040051,les Escaldes,42.50729,1.53414,AD,15853,Europe/Andorra,08,"[Ehskal'des-Ehndzhordani, Escaldes, Escaldes-Engordany, Les Escaldes, esukarudesu=engorudani jiao qu, lai sai si ka er de-en ge er da, Эскальдес-Энджордани, エスカルデス＝エンゴルダニ教区, 萊塞斯卡爾德-恩戈爾達, 萊塞斯卡爾德－恩戈爾達]"
1,3041563,Andorra la Vella,42.50779,1.52109,AD,20430,Europe/Andorra,07,"[ALV, Ando-la-Vyey, Andora, Andora la Vela, Andora la Velja, Andora lja Vehl'ja, Andoro Malnova, Andorra, Andorra Tuan, Andorra a Vella, Andorra la Biella, Andorra la Vella, Andorra la Vielha, Andorra-a-Velha, Andorra-la-Vel'ja, Andorra-la-Vielye, Andorre-la-Vieille, Andò-la-Vyèy, Andòrra la Vièlha, an dao er cheng, andolalabeya, andwra la fyla, Ανδόρρα, Андора ла Веля, Андора ла Веља, Андора ля Вэлья, Андорра-ла-Велья, אנדורה לה וולה, أندورا لا فيلا, አንዶራ ላ ቬላ, アンドラ・ラ・ヴェリャ, 安道爾城, 안도라라베야]"
2,290594,Umm Al Quwain City,25.56473,55.55517,AE,62747,Asia/Dubai,07,"[Oumm al Qaiwain, Oumm al Qaïwaïn, Um al Kawain, Um al Quweim, Umm Al Quwain City, Umm al Qaiwain, Umm al Qawain, Umm al Qaywayn, Umm al-Quwain, Umm-ehl'-Kajvajn, Yumul al Quwain, am alqywyn, mdynt am alqywyn, Умм-эль-Кайвайн, أم القيوين, مدينة ام القيوين]"
3,291074,Ras Al Khaimah City,25.78953,55.9432,AE,351943,Asia/Dubai,05,"[Julfa, Khaimah, RAK City, RKT, Ra's al Khaymah, Ra's al-Chaima, Ras Al Khaimah City, Ras al Khaimah, Ras al-Khaimah, Ras el Khaimah, Ras el Khaïmah, Ras el-Kheima, Ras-ehl'-Khajma, Ra’s al Khaymah, Ra’s al-Chaima, mdynt ras alkhymt, ras alkhymt, Рас-эль-Хайма, رأس الخيمة, مدينة رأس الخيمة]"
4,291580,Zayed City,23.65416,53.70522,AE,63482,Asia/Dubai,01,"[Bid' Zayed, Bid’ Zayed, Madinat Za'id, Madinat Zayid, Madīnat Zāyid, Madīnat Zā’id, Zayed City, mdynt zayd, مدينة زايد]"

In [62]:
# sort cities by country code and name in descending order
cities = cities.sort_values(by=["countrycode", "name"]).reset_index(drop=True)
# drop unnecessary columns
# cities = cities.drop(
#     columns=[
#         "population"
#           , "alternatenames"
#     ]
# )
# rename columns for clarity
cities = cities.rename({"geonameid": "cityid", "name": "cityname_raw"}, axis=1)
# transform all accented strings to English alphabets'
cities.insert(loc=2, column="city", value=np.nan)
cities.city = cities["cityname_raw"].apply(func=lambda x: unidecode.unidecode(string=x))

cities.head(10)

,cityid,cityname_raw,city,latitude,longitude,countrycode,population,timezone,admin1code,alternatenames
0,3041563,Andorra la Vella,Andorra la Vella,42.50779,1.52109,AD,20430,Europe/Andorra,07,"[ALV, Ando-la-Vyey, Andora, Andora la Vela, Andora la Velja, Andora lja Vehl'ja, Andoro Malnova, Andorra, Andorra Tuan, Andorra a Vella, Andorra la Biella, Andorra la Vella, Andorra la Vielha, Andorra-a-Velha, Andorra-la-Vel'ja, Andorra-la-Vielye, Andorre-la-Vieille, Andò-la-Vyèy, Andòrra la Vièlha, an dao er cheng, andolalabeya, andwra la fyla, Ανδόρρα, Андора ла Веля, Андора ла Веља, Андора ля Вэлья, Андорра-ла-Велья, אנדורה לה וולה, أندورا لا فيلا, አንዶራ ላ ቬላ, アンドラ・ラ・ヴェリャ, 安道爾城, 안도라라베야]"
1,3040051,les Escaldes,les Escaldes,42.50729,1.53414,AD,15853,Europe/Andorra,08,"[Ehskal'des-Ehndzhordani, Escaldes, Escaldes-Engordany, Les Escaldes, esukarudesu=engorudani jiao qu, lai sai si ka er de-en ge er da, Эскальдес-Энджордани, エスカルデス＝エンゴルダニ教区, 萊塞斯卡爾德-恩戈爾達, 萊塞斯卡爾德－恩戈爾達]"
2,292968,Abu Dhabi,Abu Dhabi,24.45118,54.39696,AE,1807000,Asia/Dubai,01,"[A-pu-that-pi, AEbu Saby, AUH, Aboe Dhabi, Abou Dabi, Abu Dabi, Abu Dabis, Abu Daby, Abu Daibi, Abu Dhabi, Abu Dhabi Island and Internal Islands City, Abu Dhabi emiraat, Abu Zabi, Abu Zaby, Abu Zabye, Abu Zabyo, Abu Ḍabi, Abu Ḑabi, Abu-Dabi, Abu-Dabi khot, Abu-Dabio, Abu-Dzabi, Abú Dabí, Abú Daibí, Abú Zabí, Abû Daby, Abū Dabī, Abū Z̧aby, Abū Z̧abye, Abū Z̧abyo, Abū Z̧abī, Ampou Ntampi, Ebu Dabi, Ebu Dhabi, a bu zha bi, abu dhabi, abu-dabi, abudabi, abudhabi, abw zby, abwzby, aputapi, jzyrt abwzby wjzr dakhlyt akhry, xa bud abi, Â-pu-tha̍t-pí, Äbu Saby, Əbu-Dabi, Άμπου Ντάμπι, Αμπου Νταμπι, Αμπού Ντάμπι, Абу Даби, Абу-Даби, Абу-Даби хот, Абу-Дабі, Әбу-Даби, Աբու Դաբի, אבו דאבי, أبوظبي, ئەبووزەبی, ابو ظبى, ابوظبی, ابوظہبی, جزيرة أبوظبي وجزر داخلية اخرى, अबु धाबी, अबू धाबी, আবুধাবি, ਅਬੂ ਧਾਬੀ, ଆବୁଧାବି, அபுதாபி, ಅಬು ಧಾಬಿ, അബുദാബി, අබුඩාබි, อาบูดาบี, ཨ་པོའུ་དྷ་པེ།, အဘူဒါဘီမြို့, აბუ-დაბი, አቡ ዳቢ, アブダビ, 阿布扎比, 아부다비]"
3,292953,Adh Dhayd,Adh Dhayd,25.28812,55.88157,AE,20165,Asia/Dubai,06,"[Adh Dhaid, Adh Dhayd, Al Daid, Al-Dhayd, Dayd, Dhaid, Dhayd, Duhayd, Ihaid, aldhyd, الذيد, Ḑayd]"
4,292932,Ajman City,Ajman City,25.40177,55.47878,AE,490035,Asia/Dubai,02,"[Ajman, Ajman City, Al Ajman, QAJ, Ujman, mdynt ʿjman, ʿjman, عجمان, مدينة عجمان]"
5,292913,Al Ain City,Al Ain City,24.19167,55.76056,AE,846747,Asia/Dubai,01,"[AAN, Ainas, Al Ain, Al Ain City, Al Ajn, Al Ayn, Al `Ayn, Al Ɛayn, Al ‘Ayn, Al-Ain, Al-Ajn, Al-Ayin, Al-Ayn, Al-Aïn, Ehl'-Ajn, El Ain, El-Ajn, ai yin, al ain, al-ain, al-aini, alʿyn, ela ena, mdynt alʿyn, Ел Аин, Эль-Айн, Ալ-Ային, אל-עין, العين, العین, مدينة العين, एल एन, அல் ஐன், അൽ ഐൻ, ალ-აინი, アル・アイン, 艾因, 알아인]"
6,292878,Al Fujairah City,Al Fujairah City,25.11641,56.34141,AE,86512,Asia/Dubai,04,"[Al Fujairah City, Al Fujayrah, Al-Fudjayra, Al-Fujayrah' emiraat, FJR, Fudschaira, Fudzhejra, Fujaira, Fujairah, Fujajro, Fujayrah, Fuĵajro, alfjyrt, fjyrt, fu ji la, fujaira, mdynt alfjyrt, Фуджейра, الفجيرة, فجيرة, مدينة الفجيرة, フジャイラ, 富吉拉]"
7,12047416,Al Shamkhah City,Al Shamkhah City,24.39268,54.70779,AE,61710,Asia/Dubai,01,"[Al Shamkhah City, mdynt alshamkht, مدينة الشامخة]"
8,292688,Ar Ruways,Ar Ruways,24.11028,52.73056,AE,25000,Asia/Dubai,01,"[Ar Ru'ays, Ar Ruways, Ar Ru’ays, Ar-Ruvais, Ruwais, Ар-Руваис]"
9,12042052,Bani Yas City,Bani Yas City,24.30978,54.62944,AE,80498,Asia/Dubai,01,"[Bani Yas, Bani Yas City, mdynt bny yas, مدينة بني ياس]"

#### Merge `countries` dataframes to `cities` dataframe

In [63]:
# How many different country codes are there in the cities dataframe?
len(cities.countrycode.unique())

244

> ⚠️ **Caution**: The `countries` and `cities` dataframes do not have the same number of countries. The `countries` dataframe has 252 countries, but `cities` dataframe has only 244 countries. Because of some countries not having cities in the `cities` df, we will use an outer join to merge the two dataframes. This will ensure that all countries are included, even if they do not have any cities listed in the `cities` df.

In [ ]:
city = (
    cities[["city", "population", "latitude", "longitude", "countrycode", "cityid"]]
    .merge(countries, how="left", on="countrycode", suffixes=("_city", "_country"))
    .sort_values(by=["countrycode", "city"], ascending=True)
    .reset_index(drop=True)
)
# rearrange columns for better readability
city = city[
    [
        "city",
        "countryname",
        "population",
        "capital",
        "latitude",
        "longitude",
        "countrycode",
        "cityid",
        "countryid",
    ]
]

print(city.shape)
city.head(10)

In [ ]:
# city.columns.tolist()

## Extract cities and countries from headlines

### Use regex to retrive all country and city names from headline column

In [ ]:
from re import Pattern
from typing import Any, Optional, Iterable


# def get_compiled_regex(name: str) -> Pattern[Any]:
#     """Create a regex pattern for the given name. Compiled one name at a time."""
#     regex = f"\\b{name}\\b"
#     return re.compile(regex)  # re.IGNORECASE)


def get_big_compiled_regex(namelist: Iterable) -> Pattern[Any]:
    """
    Create a regex pattern for the given name list.
    Ensures input is a list, sorts by length (descending), then compiles.
    """
    if not isinstance(namelist, list):
        namelist = list(namelist)
    namelist.sort(key=len, reverse=True)
    all_names = r"\b|\b".join(re.escape(pattern=name) for name in namelist)
    regex = f"(\\b(?:{all_names})\\b)"
    # return re.compile(regex, re.IGNORECASE)
    return re.compile(regex)

In [ ]:
# def get_matched_country(headline: str) -> Optional[str]:
#     """Extract the matched country string from a headline string by compiled one regex pattern of country at a time."""
#     # Create a compiled regex for each country name
#     for country_name in city.countryname:
#         compiled_country = get_compiled_regex(country_name)
#         # match country in headline
#         match_country = compiled_country.search(headline)
#         if match_country is not None:
#             start, end = match_country.start(), match_country.end()
#             return headline[start:end]


def get_matched_country(headline: str) -> Optional[str]:
    """Extract the matched country name string from a headline string by compiled regex pattern of all countries."""
    compiled_countries = get_big_compiled_regex(city.countryname)
    matched_countries = re.findall(compiled_countries, headline)
    return matched_countries[0] if matched_countries else None


def get_matched_city(headline: str, compiled_regex) -> Optional[str]:
    """Extract the matched city name string from a headline string by compiled regex pattern of all cities."""
    # compiled_cities = get_big_compiled_regex(city.cityname)
    matched_cities = re.findall(compiled_regex, headline)
    return matched_cities[0] if matched_cities else None


def get_matched_usstate(headline: str) -> Optional[str]:
    """Extract the matched US state name string from a headline string by compiled regex pattern of all US states."""
    compiled_states = get_big_compiled_regex(states.statename)
    matched_states = re.findall(compiled_states, headline)
    return matched_states[0] if matched_states else None


def get_matched_uscounty(headline: str) -> Optional[str]:
    """Extract the matched US county name string from a headline string by compiled regex pattern of all US counties."""
    compiled_counties = get_big_compiled_regex(us_counties.countyname)
    matched_counties = re.findall(compiled_counties, headline)
    return matched_counties[0] if matched_counties else None

    # """Extract the matched city string from a regex match object."""
    # compiled_city = get_city_regex(city_name)
    # match_city = compiled_city.search(headline)
    # if match_city is not None:
    #     start, end = match_city.start(), match_city.end()
    #     return headline[start:end]

### Cities extraction

In [ ]:
compiled_cities = get_big_compiled_regex(city.city)
df["city"] = df.headline.apply(
    func=lambda x: get_matched_city(headline=x, compiled_regex=compiled_cities)
)


print(df.shape)


df.head(10)

> 📝 **Note**:
> The `cities` extraction is done using regex to match the city names in the headlines. The regex pattern and matching sequence (lengthiest name first) is designed to capture full city names, avoiding partial matches. 
>
> - of total 648 headlines, 
>   - 606 headlines (93.5%) have city names extracted.
>   - 42 headlines (6.5%) do not have any city names extracted.

In [ ]:
df[df.city.notnull()]

In [ ]:
city[city.cityname.str.contains("Vero Beach")]

In [ ]:
print(len(df[df.city.isnull()]))
df[df.city.isnull()]

In [ ]:
city[city.cityid.duplicated(keep=False)]

### Add country names column to the DataFrame by merging with `city` dataframe

In [ ]:
merged = df.merge(
    right=city[
        [
            "countryname",
            "population",
            "cityid",
            "cityname",
            # "latitude", "longitude"
        ]
    ],
    how="left",
    left_on="city",
    right_on="cityname",
    suffixes=("_headline", "_city"),
)

merged.population = merged.population.astype(
    dtype="Int64"
)  # Use Int64 to allow for NaN values in the population column
merged

In [ ]:
merged[merged.cityid.duplicated(keep=False)].sort_values(
    by=["headline", "population", "cityid"]
)

In [ ]:
merged[merged.duplicated(subset=["headlineid"], keep=False)].sort_values(
    by=["headline", "population"]
)

> 📝 **Note**: We found 176 headlines that were matched with multiple cities the have the same name. For example, There were 3 different **"Rome"** city, one in the Italy and another two in the US. Thus, the headline **"Authorities are Worried about the Spread of Mad Cow Disease in Rome"** got three duplicates.
> What we need to do is to

### US counties extraction

In [ ]:
df["us_county"] = df.headline.apply(func=lambda x: get_matched_uscounty(x))

print(df.shape)
df.head(10)

### US States extraction

In [ ]:
# df["us_state"] = df.headline.apply(func=lambda x: get_matched_usstate(x))
# print(df.shape)
# df.head(10)


### Countries extraction

In [ ]:
df["country"] = df["headline"].apply(func=lambda x: get_matched_country(x))
print(df.shape)
df.head(10)

In [ ]:
df[df.country.notnull()]

In [ ]:
df.merge(
    right=city[["countryname", "cityname", "cityid"]],
    how="left",
    left_on="city",
    right_on="cityname",
    suffixes=("_headline", "_city"),
)

In [ ]:
df

In [ ]:
for ct_idx, ct in enumerate(countries.countryname):
    for st_idx, st in enumerate(df.headline):
        if ct in st:
            print(f"Headline: {st}\t\t\tCountry: {ct}")
            break

In [ ]:
suffix = [
    "County",
    "Municipality",
    "Municipio",
    "Census Area",
    "City and Borough",
    "Borough",
    "Parish",
    "City",
]

for s in suffix:
    print(f"\nSuffix: {s}")
    for headline in df.headline:
        print(f"\t{headline}") if s in headline else None

In [ ]:
city_regexs = []

for city in cities.name:
    #     r1 = '\\b'+city+'\\b'
    #     city_regexs.append(r1)
    r2 = city
    city_regexs.append(r2)
for state in states.name:
    r3 = "\\b" + state + "\\b"
    city_regexs.append(r3)
for county in counties.county:
    r4 = "\\b" + county + "\\b"
    city_regexs.append(r4)

ind = []
city = []
hline = []

for val in [
    "Mala",
    "Bron",
    "Viru",
    "Pati",
    "Rota",
    "Will",
    "Green",
    "\\b" + "Will" + "\\b",
]:
    for regex in city_regexs:
        if regex == val:
            city_regex = city_regexs.remove(val)

for regex in city_regexs:
    compiled_city = re.compile(regex)

    for index, headline in enumerate(df.headline):
        match = compiled_city.search(headline)
        if match is not None:
            start, end = match.start(), match.end()
            matched_string = headline[start:end]
            if len(matched_string) > 3:
                ind.append(index)
                city.append(matched_string)
                hline.append(headline)
#                 print(index,matched_string, '<<<', headline)

# Create dataframe of matched results and sort values by headline_no
matched = {"headline_no": ind, "headline": hline, "city": city}
matched_cities = pd.DataFrame(matched)
matched_cities = matched_cities.sort_values(by="headline_no").reset_index(drop=True)

matched_cities.head(n=15)

In [ ]:
cities[cities.name == "York"]

**Note: We found some interesting patterns of matched results.**

**For example**
* There were **three** matched results on a headline "Could Zika Reach New York City?"
* The first result was "New York City" which was a correct matched. 
* The rest two were "York" which could either be matched but why did we have two "York"?
* Check out on the `cities` dataframe then we found that there are two different locations of "York", one in the US and another one in the GB.

In [ ]:
# How many headline had matched result more than 1?
print("*********" * 10)
print("**** Checked duplicates ****")
print("*********" * 10)
print("\n")
print(
    str(
        len(
            matched_cities.headline.value_counts()[
                matched_cities.headline.value_counts() > 1
            ]
        )
    )
    + "/650 headlines had matched result more than 1."
)

# Drop duplicates of matched city names
matched_cities_uniq = matched_cities.drop_duplicates()

print("\n")
print(
    "Note: There were still number of headlines which had matched result more than 1. However, among those unique matched city names, only the longest string of city is the correct matched"
)
print("\n")

print("*********" * 10)
print("**** Dropped duplicates ****")
print("*********" * 10)
print("\n")
print(
    str(
        len(
            matched_cities_uniq.headline.value_counts()[
                matched_cities_uniq.headline.value_counts() > 1
            ]
        )
    )
    + "/650 headlines had matched result more than 1 after dropped duplicates."
)
print("\n")
print(
    matched_cities_uniq.headline.value_counts()[
        matched_cities_uniq.headline.value_counts() > 1
    ].head(10)
)
print("\n")


# Make a list of headlines that had matched result more than 1.
redun_headlines = matched_cities_uniq.headline.value_counts()[
    matched_cities_uniq.headline.value_counts() > 1
].index.tolist()
# Keep only the longest matched cities
for hl in redun_headlines:
    cities_to_compare = matched_cities_uniq.city[matched_cities_uniq.headline == hl]
    length_str = [
        (len(city), index)
        for index, city in list(zip(cities_to_compare.index, cities_to_compare))
    ]
    for length, index in length_str:
        if (length, index) != max(length_str):
            matched_cities_uniq.drop(index, axis=0, inplace=True)

print("\n")
print("*********" * 10)
print("**** Filtered only the longest matched cities ****")
print("*********" * 10)
print("\n")
print(
    str(
        len(
            matched_cities_uniq.headline.value_counts()[
                matched_cities_uniq.headline.value_counts() > 1
            ]
        )
    )
    + "/650 headlines had matched result more than 1 after filtered the longest."
)
matched_cities_uniq = matched_cities_uniq.reset_index(drop=False).set_index(
    "headline_no", drop=True
)
display(matched_cities_uniq.head())

In [ ]:
#  Add city column to df dataframe
df = df.join(matched_cities_uniq[["city"]])

# Manually fill the nulls in city column.
for i in df[df.city.isnull()].index:
    df.loc[i, "city"] = "Cebu "  # <<<  Zika infects pregnant woman in Cebu
    df.loc[i, "city"] = "Antigua "  # <<<  Spanish Flu Sighted in Antigua
    df.loc[i, "city"] = (
        "Rio De Janeiro"  # <<<  Carnival under threat in Rio De Janeiro due to Zika outbreak
    )
    df.loc[i, "city"] = "Oton"  # <<<  Zika case reported in Oton
    df.loc[i, "city"] = "Maka"  # <<<  Maka City Experiences Influenza Outbreak
    df.loc[i, "city"] = "Mcallen"  # <<<  More Zika patients reported in Mcallen
    df.loc[i, "city"] = (
        "Mclean"  # <<<  More people in Mclean are infected with Hepatitis A every year
    )
    df.loc[i, "city"] = "Sussex"  # <<<  Malaria Exposure in Sussex
    df.loc[i, "city"] = "Greenwich"  # <<<  Greenwich Establishes Zika Task Force
    df.loc[i, "city"] = "Yulee"  # <<<  Yulee takes a hit from Spreading Sickness
    df.loc[i, "city"] = (
        "Boucau"  # <<<  More people in Boucau are infected with HIV every year
    )
    df.loc[i, "city"] = "Manhasset"  # <<<  Bronchitis Outbreak in Manhasset
    df.loc[i, "city"] = "Padre Las Casas"  # <<<  Zika Troubles come to Padre Las Casas
    df.loc[i, "city"] = "Destin"  # <<<  Outbreak of Zika in Destin
    df.loc[i, "city"] = (
        "Gympie"  # <<<  Gympie Patient in Critical Condition after Contracting Chlamydia
    )
    df.loc[i, "city"] = "Druid Hills"  # <<<  Spike of Meningitis Cases in Druid Hills
    df.loc[i, "city"] = (
        "Magnolia"  # <<<  More Patients in Magnolia are Getting Diagnosed with Malaria
    )
    df.loc[i, "city"] = (
        "Penal"  # <<<  Rumors about Syphilis spreading in Penal have been refuted
    )
    df.loc[i, "city"] = "Lisbon"  # <<<  Spanish Flu Outbreak in Lisbon
    df.loc[i, "city"] = "Madrid"  # <<<  Spanish Flu Spreading through Madrid
    df.loc[i, "city"] = "Belvoir"  # <<<  Fort Belvoir tests new cure for Hepatitis C
    df.loc[i, "city"] = (
        "Oak Brook"  # <<<  More people in Oak Brook are infected with Respiratory Syncytial Virus every year
    )
    df.loc[i, "city"] = "Hutchins"  # <<<  Outbreak of Zika in Hutchins
    df.loc[i, "city"] = "Longwood"  # <<<  Longwood volunteers spreading Zika awareness
    df.loc[i, "city"] = "Quixere"  # <<<  Zika symptoms spotted in Quixere
    df.loc[i, "city"] = "Davos"  # <<<  Measles Hits Davos
    df.loc[i, "city"] = (
        "Morehead City"  # <<<  Spike of Hepatitis E Cases in Morehead City
    )
    df.loc[i, "city"] = "Alvorad"  # <<<  Outbreak of Zika in Alvorada
    df.loc[i, "city"] = "Dangriga"  # <<<  Zika arrives in Dangriga
    df.loc[i, "city"] = (
        "Maynard"  # <<<  More Patients in Maynard are Getting Diagnosed with Syphilis
    )
    df.loc[i, "city"] = "Antioquia"  # <<<  Zika case reported in Antioquia
    df.loc[i, "city"] = "Pismo Beach"  # <<<  Chikungunya has not Left Pismo Beach
    df.loc[i, "city"] = "La Joya"  # <<<  Zika spreads to La Joya
#     print("df.loc[i,'city'] = '' #<<< ",df.loc[i,'headline'] ,"\n")
df.info()

In [ ]:
df.head(50)

In [ ]:
# Save to csv file
# df.to_csv("cities_in_headline.csv", index=None)